import "../controllers/presets/createUsers.js"
import "../controllers/presets/createProducts.js"
import "../controllers/presets/createBlogPosts.js"
import "../controllers/presets/createComments.js"
import "../controllers/customDataType.js"
import "../controllers/registerApi.js"
import "../controllers/registerApiWithAi.js"